# Generated by Django 2.2.6 on 2019-10-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.TextField()),
                ('item', models.CharField(max_length=200)),
                ('price', models.TextField(max_length=20)),
            ],
        ),
    ]
